# Do not use Kong Ingress Controller
ingressController:
  enabled: false
   
image:
  repository: kong/kong-gateway
   
# Mount the secret created earlier
secretVolumes:
  - kong-dp-cert

# Default auto-scaling using HPA
#autoscaling:
#  enabled: true
#  minReplicas: 3
#  maxReplicas: 10
#  targetCPUUtilizationPercentage: 50

env:
  # data_plane nodes do not have a database
  role: data_plane
  database: "off"
   
  # Tell the data plane how to connect to the control plane
  cluster_control_plane: kong-cp-kong-cluster.kong.svc.cluster.local:8005
  cluster_telemetry_endpoint: kong-cp-kong-clustertelemetry.kong.svc.cluster.local:8006
  #cluster_telemetry_server_name: kong_clustering
   
  # Configure control plane / data plane authentication
  cluster_mtls: pki
  cluster_ca_cert: /etc/secrets/kong-dp-cert/ca.crt
  cluster_cert: /etc/secrets/kong-dp-cert/dp.crt
  cluster_cert_key: /etc/secrets/kong-dp-cert/dp.key
  lua_ssl_trusted_certificate: /etc/secrets/kong-dp-cert/ca.crt

  log_level: debug

  status_listen: 0.0.0.0:8100
   
# Enterprise functionality
enterprise:
  enabled: true
  license_secret: kong-enterprise-license
   
# The data plane handles proxy traffic only
proxy:
  enabled: true
  type: ClusterIP
  labels:
    enable-metrics: "true"

serviceMonitor:
  enabled: true
  http:
    enabled: true
    containerPort: 8100

status:
  enabled: true
  http:
    enabled: true
    containerPort: 8100

extraObjects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: kong-dp-status
      namespace: kong
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8100"
    spec:
      type: ClusterIP
      ports:
        - name: status
          port: 8100
          targetPort: 8100
          protocol: TCP
      selector:
        app.kubernetes.io/name: kong
        app.kubernetes.io/component: app
        app.kubernetes.io/instance: kong-dp
   
# These roles are served by the kong-cp deployment
admin:
  enabled: false
   
manager:
  enabled: false